name: "[QA] Quality Checks API"

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'runner/*'
      - 'sdk/*'
  push:
    paths:
      - 'runner/*'
      - 'sdk/*'

jobs:
  quality-checks:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: read
      checks: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23.2

      - name: Linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.62.2
          args: --config .github/.golangci.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Tests
        run: go test ./... --tags=integration,unit -cover -v
